const ARCHIVE=window.TIKTOK_ARCHIVE_DATA;
const key=document.body.dataset.collection;
const collection=ARCHIVE.collections[key];
const VIDEOS=collection.videos;
const copy={
  en:{videos:"VIDEOS",source:"SOURCE",year:"YEAR",sort:"SORT",sourceFolder:"OPEN SOURCE FOLDER",empty:"TRY CHANGING THE SEARCH OR FILTERS.",tiktokArchive:"TIKTOK ARCHIVE",backTop:"BACK TO TOP",download:"DOWNLOAD",openOriginal:"OPEN ORIGINAL",playerNote:"THE VIDEO IS PLAYED DIRECTLY FROM THE PUBLIC ARCHIVE ON GOOGLE DRIVE.",allYears:"ALL YEARS",search:"SEARCH VIDEOS...",newest:"NEWEST FIRST",oldest:"OLDEST FIRST",az:"A—Z",allVideos:"ALL VIDEOS",play:"PLAY VIDEO",loadMore:"LOAD MORE ↓",unknown:"DATE UNKNOWN"},
  ko:{videos:"영상",source:"출처",year:"연도",sort:"정렬",sourceFolder:"원본 폴더 열기",empty:"검색어나 필터를 변경해 보세요.",tiktokArchive:"틱톡 아카이브",backTop:"맨 위로",download:"다운로드",openOriginal:"원본 열기",playerNote:"영상은 공개 Google Drive 아카이브에서 사이트 안에 직접 재생됩니다.",allYears:"전체 연도",search:"영상 검색...",newest:"최신순",oldest:"오래된순",az:"가나다순",allVideos:"전체 영상",play:"영상 재생",loadMore:"더 보기 ↓",unknown:"날짜 미상"}
};
const state={lang:localStorage.getItem("tbzTikTokLang")||"en",year:"all",query:"",sort:"newest",shown:24,current:null};
const $=selector=>document.querySelector(selector);
const grid=$("#videoGrid"),search=$("#search"),yearFilter=$("#yearFilter"),sortFilter=$("#sortFilter"),tabs=$("#yearTabs"),loadMore=$("#loadMore"),dialog=$("#playerDialog");
const esc=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const thumb=id=>`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w1000`;
const preview=id=>`https://drive.google.com/file/d/${encodeURIComponent(id)}/preview`;
const original=id=>`https://drive.google.com/file/d/${encodeURIComponent(id)}/view`;
const download=id=>`https://drive.google.com/uc?export=download&id=${encodeURIComponent(id)}`;
const duration=value=>{if(!value)return"";const total=Math.round(value/1000),minutes=Math.floor(total/60),seconds=String(total%60).padStart(2,"0");return `${minutes}:${seconds}`};
const dateLabel=(video,L)=>video.date?video.date.replaceAll("-","."):(video.year||L.unknown);
const chronology=video=>`${String(video.year).padStart(4,"0")}|${(video.date||"").replaceAll("-","")}|${video.tiktokId||""}`;
const YEARS=[...new Set(VIDEOS.map(video=>video.year).filter(Boolean))].sort((a,b)=>b-a);
function setup(){YEARS.forEach(year=>yearFilter.insertAdjacentHTML("beforeend",`<option value="${year}">${year}</option>`));$("#videoCount").textContent=VIDEOS.length.toLocaleString("en-US");$("#yearRange").textContent=YEARS.length?(YEARS.length===1?String(YEARS[0]):`${Math.min(...YEARS)}—${Math.max(...YEARS)}`):"—";$("#sourceLink").href=`https://drive.google.com/drive/folders/${encodeURIComponent(collection.folderId)}`;renderTabs()}
function renderTabs(){const L=copy[state.lang];tabs.innerHTML=`<button class="${state.year==="all"?"selected":""}" data-year="all">${L.allYears}</button>`+YEARS.map(year=>`<button class="${String(state.year)===String(year)?"selected":""}" data-year="${year}">${year}</button>`).join("")}
function filtered(){let list=VIDEOS.filter(video=>(state.year==="all"||video.year===Number(state.year))&&(!state.query||(video.title+" "+video.originalName).toLocaleLowerCase().includes(state.query)));list=[...list];if(state.sort==="oldest")list.sort((a,b)=>chronology(a).localeCompare(chronology(b)));else if(state.sort==="az")list.sort((a,b)=>a.title.localeCompare(b.title));else list.sort((a,b)=>chronology(b).localeCompare(chronology(a)));return list}
function renderVideos(){const L=copy[state.lang],list=filtered(),visible=list.slice(0,state.shown);$("#resultsLabel").textContent=`${state.year==="all"?L.allVideos:state.year} · ${list.length.toLocaleString("en-US")}`;grid.innerHTML=visible.map((video,index)=>`<article class="video-card"><button class="video-thumb" type="button" data-play="${esc(video.id)}" aria-label="${esc(L.play+": "+video.title)}"><img src="${thumb(video.id)}" alt="" loading="lazy"><span class="video-number">${String(index+1).padStart(3,"0")}</span><span class="play-badge">▶ ${L.play}</span></button><div class="video-info"><div class="eyebrow">${esc(collection.name)} · ${dateLabel(video,L)}</div><h2>${esc(video.title)}</h2><div class="video-meta"><span>${video.year||"—"}</span><span>${duration(video.duration)}</span></div><div class="video-actions"><button type="button" data-play="${esc(video.id)}">${L.play} →</button><a href="${download(video.id)}" target="_blank" rel="noopener noreferrer">${L.download} ↓</a></div></div></article>`).join("");$("#empty").hidden=list.length>0;loadMore.hidden=state.shown>=list.length;loadMore.textContent=L.loadMore}
function openPlayer(id){const video=VIDEOS.find(item=>item.id===id);if(!video)return;state.current=video;const L=copy[state.lang];$("#playerTitle").textContent=video.title;$("#playerKicker").textContent=`${collection.name} · ${dateLabel(video,L)}${duration(video.duration)?" · "+duration(video.duration):""}`;$("#downloadVideo").href=download(video.id);$("#originalVideo").href=original(video.id);$("#playerFrame").src=preview(video.id);dialog.showModal();document.body.classList.add("player-open")}
function applyLanguage(){const L=copy[state.lang];document.documentElement.lang=state.lang==="ko"?"ko":"en";$("#langToggle").textContent=state.lang==="ko"?"KOR":"EN";document.querySelectorAll("[data-i18n]").forEach(element=>element.textContent=L[element.dataset.i18n]);search.placeholder=L.search;yearFilter.options[0].textContent=L.allYears;sortFilter.options[0].textContent=L.newest;sortFilter.options[1].textContent=L.oldest;sortFilter.options[2].textContent=L.az;renderTabs();renderVideos();if(state.current&&dialog.open)$("#playerKicker").textContent=`${collection.name} · ${dateLabel(state.current,L)}${duration(state.current.duration)?" · "+duration(state.current.duration):""}`}
search.addEventListener("input",event=>{state.query=event.target.value.trim().toLocaleLowerCase();state.shown=24;renderVideos()});yearFilter.addEventListener("change",event=>{state.year=event.target.value;state.shown=24;renderTabs();renderVideos()});sortFilter.addEventListener("change",event=>{state.sort=event.target.value;renderVideos()});tabs.addEventListener("click",event=>{const button=event.target.closest("button[data-year]");if(!button)return;state.year=button.dataset.year;yearFilter.value=state.year;state.shown=24;renderTabs();renderVideos()});grid.addEventListener("click",event=>{const target=event.target.closest("[data-play]");if(target)openPlayer(target.dataset.play)});loadMore.addEventListener("click",()=>{state.shown+=24;renderVideos()});$("#closePlayer").addEventListener("click",()=>dialog.close());dialog.addEventListener("close",()=>{document.body.classList.remove("player-open");$("#playerFrame").src="about:blank";state.current=null});dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});$("#langToggle").addEventListener("click",()=>{state.lang=state.lang==="en"?"ko":"en";localStorage.setItem("tbzTikTokLang",state.lang);applyLanguage()});
setup();applyLanguage();
